### PR TITLE
fixed bug of selling negative cow amounts

### LINKED ISSUE #8: BUG: Disallow selling negative cow amounts
### Have you updated the title?

- [X] I have updated the issue's title.

### Summary

When inputting a value into the field, a user can input a negative value that updates the number of cows and wealth when it should not.

### Expected Behavior

The user should see a popup similar to:

Screenshot 2024-02-21 at 4 34 57 PM

indicating that you should not be able to sell negative cows.

The number of cows and wealth should not be affected.

### Current / Observed Behavior

Currently, you can input a negative value which allows you to sell a negative number of cows - which doesn't make sense. 

Screenshot 2024-02-21 at 4 39 13 PM

The wealth and # of cows values are updated accordingly with negative values as well.

### Steps to Reproduce

1. Click sell cows. Input a negative value into the box
Screenshot 2024-02-21 at 4 45 19 PM
2. Observe how the values of # cows and wealth change incorrectly.
Screenshot 2024-02-21 at 4 48 29 PM

### Browser / Platform Info

Chrome on MacOS

### PR DESCRIPTION
**Pull request by bonniehuynh**
## Overview
In this PR, the user can no longer sell a negative amount of cows. They are given an error message that says "You cannot sell a negative number of cows!"

Changes deployed at Dokku deployment here: https://happycows-bonniehuynh-dev.dokku-03.cs.ucsb.edu/

## Tests
In the UserCommonsControllerTests.java file, I added a function called test_SellCow_commons_exists_sell_negative_cows() to give a bad request if the given a negative number of cows to sell.
Screenshot of the test for the bug:
Screenshot 2024-02-29 at 4 40 13 pm

Closes #8

### CODE REVIEW

**Comment by srambhatla30** [comment]
Matches the way I implemented my changes for the negative buy fix, LGTM.

**Review by srambhatla30 — APPROVED** [review]
Matches the way I solved the negative buy amount bug, LGTM

**Review by sangitakunapuli — APPROVED** [review]
LGTM - just pull main into this to update

**Review by sangitakunapuli — CHANGES_REQUESTED** [review]
actually, please delete the stryker tmp file and recommit so you don’t have 403 files changed in this PR

**Review by sangitakunapuli — APPROVED** [review]
LGTM

**Pull request merged**
